### PR TITLE
Update code documentation

### PR DESCRIPTION
**Pull request by andrianfaa**
This PR Updates the inline code documentation

### CODE REVIEW

**Review by ahqsoftwares — APPROVED** [review]
Great 🎉

**Comment by ahqsoftwares** [comment]
@Rstacx This is ready to be merged

**Comment by ahqsoftwares** [comment]
@andrianfaa Can you bump the version to v3.0.4

**Comment by andrianfaa** [comment]
> @andrianfaa Can you bump the version to v3.0.4

Sure!

**Comment by Rstacx** [comment]
> > @andrianfaa Can you bump the version to v3.0.4
> 
> Sure!

You have come to the discord server. Say that I am the updater and then give the easy collaborator role

**Pull request merged**
